name: monk-coder
on:
  schedule:
    - cron: '32 */6 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-monk-coder
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync monk-coder
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/monk-coder/dust.git"
          source_branch: "dust"
          destination_branch: "monk-coder_dust"
          github_token: ${{ secrets.PAT }}
