name: passerby-b-javascript
on:
  schedule:
    - cron: '38 */6 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-passerby-b-javascript
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync passerby-b-javascript
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://gitee.com/passerby-b/javascript.git"
          source_branch: "master"
          destination_branch: "passerby-b_javascript"
          github_token: ${{ secrets.PAT }}
