name: songyangzz
on:
  schedule:
    - cron: '46 */6 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-songyangzz
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync songyangzz
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/songyangzz/QuantumultX.git"
          source_branch: "master"
          destination_branch: "Sunert_QuantumultX"
          github_token: ${{ secrets.PAT }}
