name: ZCY01
on:
  schedule:
    - cron: '33 1 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-ZCY01
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync ZCY01
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/ZCY01/daily_scripts.git"
          source_branch: "main"
          destination_branch: "ZCY01_daily_scripts"
          github_token: ${{ secrets.PAT }}
