name: zZPiglet
on:
  schedule:
    - cron: '38 */6 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-zZPiglet
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync zZPiglet
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/zZPiglet/Task.git"
          source_branch: "master"
          destination_branch: "zZPiglet_Task"
          github_token: ${{ secrets.PAT }}
